config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 2000 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username,  presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,     presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully!"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully!"
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if logged_in?
  end
  
  def about
  
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own user profile"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block shadow-sm")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
    <div class="row mt-4 justify-content-md-center">
        <div class="col-8">
            <div class="card text-center shadow-sm rounded-lg">
                <div class="card-header font-italic">
                <% if article.user %>
                    by <%= link_to article.user.username, user_path(article.user) %>
                <% end %>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-dark" %></h5>
                    <div class="card-text text-left"><%= simple_format(truncate(article.description, length: 100)) %></div>
                    <%= link_to 'Show', article_path(article), class: "btn btn-outline-primary" %>
                    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
                        <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(article.created_at) %> ago,
                    edited <%= time_ago_in_words(article.updated_at) %> ago.</small>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_articles.html.erb
<% @articles.each do |article| %>
    <div class="row mt-4 justify-content-md-center">
        <div class="col-8">
            <div class="card text-center shadow-sm rounded-lg">
                <div class="card-header font-italic">
                <% if article.user %>
                    by <%= link_to article.user.username, user_path(article.user) %>
                <% end %>
                <div class="mt-2">
                    <%= render article.categories %>
                </div>
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-dark" %></h5>
                    <div class="card-text text-left"><%= simple_format(truncate(article.description, length: 100)) %></div>
                    <%= link_to 'Show', article_path(article), class: "btn btn-outline-primary" %>
                    <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info" %>
                        <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(article.created_at) %> ago,
                    edited <%= time_ago_in_words(article.updated_at) %> ago.</small>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<div class="row justify-content-center mt-4">
    <div class="col-10">
        <%= form_with(model: @article, class: "shadow-sm p-4 mb-3 bg-light rounded-lg", local: true) do |f| %>

            <div class="form-group row">
                <div class="col-2 col-form-label">
                    <%= f.label :title, class: "text-dark" %>
                </div>
                <div class="col-10">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-2 col-form-label">
                    <%= f.label :description, class: "text-dark" %><br/>
                </div>
                <div class="col-10">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-2 col-form-label">
                    <%= f.label :category, class: "text-dark" %><br/>
                </div>
                <div class="col-10">
                    <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Choose the article categories (can be empty)" }, { multiple: true, class: "custom-select", size: 5 }) %>
                </div>
            </div>

            <div class="form-group row justify-content-center">
                <%= f.submit class:"btn btn-outline-dark btn-lg" %>
            </div>


        <% end %>
    </div>
    <div class="form-group row col-12 justify-content-center">
        [ <%= link_to 'Cancel and return to articles index', articles_path, class: "text-dark" %> ]
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit article</h1>

<%= render 'shared/errors', obj: @article %>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center">Listing all articles</h1>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles' %>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Create a new article</h1>

<%= render 'shared/errors', obj: @article %>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center"><%= @article.title %></h1>
<div class="row mt-4 justify-content-md-center">
    <div class="col-8">
        <div class="card text-center shadow-sm rounded-lg">
            <div class="card-header font-italic">
                by <%= @article.user.username if @article.user %>
                <%= link_to gravatar_for(@article.user, size: 60), user_path(@article.user) %>
                <% if @article.categories.any? %>
                    <div class="mt-2">
                        <%= render @article.categories %>
                    </div>
                <% end %>
            </div>
            <div class="card-body">
                <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                <% if logged_in? && (@article.user == current_user  || current_user.admin?) %>
                    <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info" %>
                    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
                <% end %>
            </div>
            <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
                edited <%= time_ago_in_words(@article.updated_at) %> ago.</small>
            </div>
        </div>
    </div>
</div>
<div class="form-group row justify-content-center mt-4">
    [ <%= link_to 'Return to articles index', articles_path, class: "text-dark" %> ]
</div>

app/views/categories/_categories.html.erb
<% @categories.each do |category| %>
    <div class="row mt-4 justify-content-md-center">
        <div class="col-6">
            <div class="card text-center shadow-sm rounded-lg">
                <div class="card-body">
                    <h3 class="card-title"><%= link_to category.name, category_path(category), class: "text-dark" %></h5>
                    <div class="card-text mt-3"><%= pluralize(category.articles.count, "article") %></div>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(category.created_at) %> ago,
                    edited <%= time_ago_in_words(category.updated_at) %> ago.</small>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-info mr-1" %>

app/views/categories/_form.html.erb
<div class="row justify-content-center mt-4">
    <div class="col-10">
        <%= form_with(model: @category, class: "shadow-sm p-4 mb-3 bg-light rounded-lg", local: true) do |f| %>

            <div class="form-group row">
                <div class="col-12">
                    <%= f.text_field :name, class: "form-control", placeholder: "Enter a category name" %>
                </div>
            </div>

            <div class="form-group row justify-content-center">
                <%= f.submit class:"btn btn-outline-dark btn-lg" %>
            </div>

        <% end %>
    </div>
    <% if @category.valid? %>
        <div class="form-group row col-12 justify-content-center">
            [ <%= link_to 'Cancel and return to category', category_path(@category), class: "text-dark" %> ]
        </div>
    <% end %>
    <div class="form-group row col-12 justify-content-center">
        [ <%= link_to 'Cancel and return to category index', categories_path, class: "text-dark" %> ]
    </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit <%= @category.name %> category</h1>

<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center">Listing all categories</h1>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @categories %>
    </div>
    <%= will_paginate @categories, :container => false %>
</div>

<%= render 'categories' %>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @categories %>
    </div>
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center">Create a new category</h1>

<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center">Category: <%= @category.name %></h1>

<div class="text-center">
    <% if logged_in? && current_user.admin? %>
        <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-info my-4" %>
        <%= link_to 'Delete category', category_path(@category), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</div>

<h3 class="text-center"><%= @category.name %> Articles</h3>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/articles' %>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Level 7 Web Dev", "https://github.com/level7webdev" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
    <div class="container">
        <% flash.each do |name, msg| %>
            <div class="row justify-content-center mt-4">
                <div class="col-8">
                    <div class="alert alert-<%= name === "alert" ? "danger" : name === "notice" ? "success" : "info" %> alert-dismissalbe fade show shadow-sm p-4 mb-3" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <%= msg %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-light">
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "About",  about_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="articleDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="articleDropdown">
              <%= link_to "Articles Index", articles_path, class: "dropdown-item" %>
              <% if logged_in? %>
                <div class="dropdown-divider"></div>
                <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="categoryDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="categoryDropdown">
              <%= link_to "Categories Index", categories_path, class: "dropdown-item" %>
              <% if logged_in? && current_user.admin? %>
                <div class="dropdown-divider"></div>
                <%= link_to "New Category", new_category_path, class: "dropdown-item" %>
              <% end %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Users",  users_path, class: "nav-link" %>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="profileDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
              </a>
              <div class="dropdown-menu" aria-labelledby="profileDropdown">
                <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
                <% if logged_in? %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
                  <%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "Log out",  logout_path, class: "nav-link", method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login",  login_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up",  signup_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input
            class="form-control mr-sm-2"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
            Search
          </button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    
    <%= render 'layouts/navigation' %>
    
    <div id="page-content">
      <div class="container my-4">
    

        <%= render 'layouts/messages' %>
        <%= yield %>

      </div>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron text-center text-light shadow" id="jumbotron-about">
    <div class="conent">
        <h3 class="display-4 my-3">About this blog</h3>
        <p class="lead">Lorem ipsum dolor sit amet, eum libris ornatus antiopam in. Nec ancillae aliquando in. Sed no reque errem, vel volutpat gubergren assueverit ad. Usu dolor epicurei definitiones ei, vide animal denique id usu. Mea oratio partem in, unum scripta comprehensam est eu, mea cu soleat vituperata.</p>
        <p>Probo verear molestie at vim, sit et postea alienum copiosae. Assentior scripserit at pro, no probo tation impetus eos. Sit elit vivendo at, pri voluptua apeirian gubergren ne, sit eu etiam urbanitas. Ne has wisi liber oratio.</p>
        <p>Laudem nominavi antiopam ei quo. An omnis volumus nam. Libris definiebas te vel. Eam in etiam nulla, ius no hinc explicari.</p>
        <p>Ei oblique voluptatum mea, vis ne movet postulant. Probo repudiare duo ad. Sed ignota iisque facilisi no, no eos velit minim labitur, integre salutandi abhorreant ut eos. Quis eirmod et nec, eu adhuc theophrastus nec.</p>
        <p>An vim sanctus qualisque democritum, definiebas complectitur at nam. Altera nusquam concludaturque usu et, his ut altera facilisis. In duo argumentum concludaturque, id atomorum argumentum scriptorem pri. Quo utroque facilis iudicabit in, in per euismod quaerendum, mea in elit ornatus.</p>
    </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center text-white shadow" id="jumbotron-home">
    <h1 class="display-2 my-5">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row justify-content-center mt-4">
        <div class="col-10">
            <div class="alert alert-danger alert-dismissalbe fade show shadow-sm p-4 mb-3" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="alert-heading ">Warning!</h4>
                <hr>
                <p>The following errors prevented the <%= obj.class.name.downcase %> from being saved:</p>
                <ul>
                    <% obj.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_user.html.erb
<% @users.each do |user| %>
    <div class="row mt-4 justify-content-md-center">
        <div class="col-8">
            <div class="card text-center shadow-sm rounded-lg">
                <div class="card-header font-italic text-dark">
                    <%= link_to user.username, user %>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to gravatar_for(user, size: 150), user %>
                    </h5>
                    <div class="card-text my-3"><%= pluralize(user.articles.count, "article") %></div>
                    <%= link_to 'View Profile', user, class: "btn btn-outline-primary" %>
                    <% if logged_in? %>
                        <% if user == current_user %>
                            <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-info" %>
                        <% end %>
                        <% if current_user.admin? %>
                            <%= link_to 'Delete User', user_path(user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                        <% end %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Joined <%= time_ago_in_words(user.created_at) %></small>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_users.html.erb
<% @users.each do |user| %>
    <div class="row mt-4 justify-content-md-center">
        <div class="col-8">
            <div class="card text-center shadow-sm rounded-lg">
                <div class="card-header font-italic text-dark">
                    <%= link_to user.username, user %>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to gravatar_for(user, size: 150), user %>
                    </h5>
                    <div class="card-text my-3"><%= pluralize(user.articles.count, "article") %></div>
                    <%= link_to 'View Profile', user, class: "btn btn-outline-primary" %>
                    <% if logged_in? %>
                        <% if user == current_user %>
                            <%= link_to 'Edit Profile', edit_user_path(user), class: "btn btn-outline-info" %>
                        <% end %>
                        <% if current_user.admin? %>
                            <%= link_to 'Delete User', user_path(user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                        <% end %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>Joined <%= time_ago_in_words(user.created_at) %></small>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your profile</h1>

<%= render 'shared/errors', obj: @user %>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center">Alpha Blog Users</h1>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
</div>

<%= render 'users' %>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Alpha Blog User Signup</h1>

<%= render 'shared/errors', obj: @user %>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.username %>'s Profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center">
    <% if logged_in? && @user == current_user %>
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info my-4" %>
        <%= link_to 'Delete User', user_path(@user), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
</div>

<h3 class="text-center"><%= @user.username %>'s Articles</h3>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/articles' %>

<div class="apple_pagination my-4">
    <div class="page_info">
        <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
</div>